### ISSUE TITLE
Timeout with Cards.all()

### ISSUE THREAD

**Issue by Tilican** [Yuudaari/scryfall-sdk#1]
Hi,
With your sdk i get an ETIMEOUT when i try to Cards.all() after 10 minutes. But all cards are not fetched

**Comment by Yuudaari** [comment]
Thanks, I’ll take a look when I get a chance.

**Comment by Yuudaari** [comment]
Hmm, I was able to do it.
```ts
const emitter = Scry.Cards.all();
emitter.on("data", (card) => {
	
}).on("end", () => {
	console.log("finished all cards");
});
```
This finished in 7 minutes for me. As the requests are separated by page, the only reason it should timeout is if it doesn't have connection to scryfall. I don't know when I'll get around to it but at some point I'll add some redundancy the requests. (so that if one fails it tries again before erroring)

**Comment by Tilican** [comment]
I fetch and store all cards on my database and update cards just one time per day for price.

**Comment by Yuudaari** [comment]
Thanks for that, but I need more information, such as the code you’re using to handle this request (maybe something you’re doing is something I didn’t expect, so it breaks?) and if this is consistent. Can you reproduce it every time? I was not able to reproduce your issue based on what you’ve told me.
